name: Test

on:
  push:

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Test
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0
      # from https://github.com/palewire/install-python-pipenv-pipfile/commits/main
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@fae3f6a0c5e68b98df1a416a3bf3f567db461251
        with:
          python-version: '3.9'
      - name: Install library
        run: |
          pipenv run install_local
      - name: Run tests
        run: |
          pipenv run coverage run -m pytest
      - name: Generate report
        run: |
          pipenv run coverage report
      - name: Generate HTML report
        run: |
          pipenv run coverage html
      - name: Upload HTML report
        # from https://github.com/actions/upload-artifact/commits/v4.6.2/
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage_html
          path: htmlcov
